<?php
//BOXES
define('NODATA', 'NESSUN DATO DA MOSTRARE');
define('ND', 'NON DEFINITO PER QUESTO TIPO DI UTENTE');
define('NDB', 'NON DEFINITO PER QUESTO TIPO DI BOX');
define('NOIMGS', 'IL TUO ALBUM NON CONTIENE IMMAGINI');
define('NOLSNGLST', 'NESSUN DATO SUL ULTIMO BRANO ASCOLTATO');
define('NOLSTEVNT', 'NESSUN DATO SULL&apos;ULTIMO EVENTO A CUI HAI PARTECIPATO');
define('IAL', 'INFO PRECEDENTEMENTE CARICATE');
define('NOTAG', 'NESSUN TAG');
define('NOATTENDEE', 'NESSUN PARTECIPANTE A QUESTO EVENTO PER ORA');
define('NOFEATEVE', 'NESSUN FEATURING PER QUESTO EVENTO');
define('NOINVITED', 'NESSUN INVITATO A QUESTO EVENTO');
define('NOTRACK', 'LA TUA TRACKLIST NON CONTIENE CANZONI');
define('NOFOLLOWING', 'NON STAI ANCORA SEGUENDO NESSUNO');
define('NOFRIENDS', 'NON HAI ANCORA AMICI');
define('NOFOLLOWERS', 'NON HAI ANCORA FOLLOWERS');
define('NOVENUE', 'NESSUNA COLLABORAZIONE CON VENUE AL MOMENTO');
define('NOJAMMER', 'NESSUNA COLLABORAZIONE CON JAMMER AL MOMENTO');

//CONTROLLERS
define('POSTSAVED', 'Il tuo post è stato salvato');
define('SHORTPOST', 'Dimensione post troppo corta | lungh:');
define('LONGPOST', 'Dimensione post troppo lunga | lungh:');
define('NOTOUSER', 'toUser non specificato');
define('NOFROMUSER', "fromUser  non specificato");
define('NOPOST', 'Post non specificato');
define('NOCOMMENT', 'Commento non specificato');
define('SHORTCOMMENT', 'Dimensione commento troppo corta | lungh:');
define('LONGCOMMENT', 'Dimensione commment troppo lunga | lungh:');
define('COMMENTSAVED', 'Il tuo commento è stato salvato');
define('ROLLKO', 'ROLLBACK KO');
define('ROLLOK', 'ROLLBACK OK');
define('CND', 'Impossibile eliminare questo elemento: non sei il proprietario');
define('SBJ', 'Il tuo account è stato cancellato');
define('DELERR', 'Errore in fase di cancellazione');
define('LOVEPLUSERR', 'Errore incrementando Love');
define('LOVEMINUSERR', 'Error decrementando Love');
define('NOMESSAGE', 'Messaggio non specificato');
define('MESSAGESAVED', 'Messaggio inviato');
define('RELDENIED', 'Invio relazione negato');
define('SELF', 'Non essere timido, invia la richiesta di relazione ad altri!');
define('SBJ', 'Richiesta di relazione');
define('SBJOK', 'Richiesta di relazione accettata');
define('RELSAVED', 'La tua richiesta è stata correttamente inviata');
define('NORELDEL', 'Nessuna relazione da cancellare');
define('SBJE', 'Il tuo evento ha ricevuto una recensione');
define('SBJR', 'Il tuo record ha ricevuto una recensione');
define('NOREW', 'Nessuna recensione specificata');
define('SHORTREW', 'Dimensione recensione troppo corta | lungh:');
define('LONGREW', 'Dimensione recensione troppo lunga | lungh:');
define('REWSAVED', 'Recensione salvata con successo');
define('NOLOGIN', 'Credenziali di accesso non valide');
define('OKLOGIN', 'Login eseguito');
define('NOLOGOUT', 'Impossibile effettuare logout');
define('OKLOGOUT', 'Logout Eseguito');

//mail di sistema
define('USERDELETED', 'it.userDeletion.html');
define('FRINDSHIPREQUESTEMAIL', 'it.friendshipRequest.html');
define('COLLABORATIONREQUESTEMAIL', 'it.collaborationRequest.html');
define('FOLLOWINGEMAIL', 'it.following.html');
define('EVENTREVIEWEMAIL', 'it.eventReviewReceived.html');
define('RECORDREVIEWEMAIL', 'it.recordReviewReceived.html');
define('FRIENDSHIPACCEPTEDEMAIL', 'it.friendshipRequestAccepted.html');
define('COLLABORATIONACCEPTEDEMAIL', 'it.collaborationRequestAccepted.html');

//RESTCONTROLLER
define('100','Continua');
define('101','Cambio Di Protocolli');
define('200','OK');
define('201','Creato');
define('202','Accettato');
define('203','Informazione Non Interessante');
define('204','Nessun Contenuto');
define('205','Reset del contenuto');
define('206','Contenuto Parziale');
define('300','Scelta Multipla');
define('301','Spostato Definitivamente');
define('302','Trovato');
define('303','Vedi Altro');
define('304','Non MOdificato');
define('305','Usa Proxy');
define('306','(Non Usato)');
define('307','Redirect Temporaneo');
define('400','Richiesta Non Valida');
define('401','Non Autorizzato');
define('402','Richiesto Pagamento');
define('403','Non Consentito');
define('404','Non Trovato');
define('405','Metodo Non Consentito');
define('406','Non Accettato');
define('407','Richiesta Autenticazione Proxy');
define('408','Richiesta Time Out');
define('409','Conflitto');
define('410','Andato');
define('411','Lunghezza richiesta');
define('412','Requisito Non Soddisfatto');
define('413','Request Entity Troppo Estesa');
define('414','Request-URI Troppo Lungo');
define('415','Media Non Supportato');
define('416','Requested Range Not Satisfiable');
define('417','Richiesta Fallita');
define('500','Errore Server');
define('501','Non Implementato');
define('502','Gateway Non Valido');
define('503','Servizio Non Disponibile');
define('504','Gateway Timeout');
define('505','Versione HTTP Non Supportata');
//USER
define('DEFAVATAR', '/var/www/vhosts/socialmusicdiscovering.com/httpdocs/images/default/dafultAvatar.jpg');
define('DEFTHUMB', '/var/www/vhosts/socialmusicdiscovering.com/httpdocs/images/default/dafultAvatarThumb.jpg');
define('DEFBGD', '/var/www/vhosts/socialmusicdiscovering.com/httpdocs/images/default/dafultBackground.jpg');

//ALBUM
define('DEFALBUMCOVER', '/var/www/vhosts/socialmusicdiscovering.com/httpdocs/images/default/dafultAlbumCover.jpg');
define('DEFALBUMTHUMB', '/var/www/vhosts/socialmusicdiscovering.com/httpdocs/images/default/dafultAlbumThumb.jpg');
//EVENT
define('DEFEVENTTHUMB', '/var/www/vhosts/socialmusicdiscovering.com/httpdocs/images/default/dafultEventThumb.jpg');
define('DEFEVENTIMAGE', '/var/www/vhosts/socialmusicdiscovering.com/httpdocs/images/default/dafultEventImage.jpg');
//RECORD
define('DEFRECORDCOVER', '/var/www/vhosts/socialmusicdiscovering.com/httpdocs/images/default/dafultRecordCover.jpg');
define('DEFRECORDTHUMB', '/var/www/vhosts/socialmusicdiscovering.com/httpdocs/images/default/dafultRecordThumb.jpg');
//SONG
define('DEFSONGTHUMB', '/var/www/vhosts/socialmusicdiscovering.com/httpdocs/images/default/dafultSongThumb.jpg');

//SETTINGS JAMMER
define('JAMMER_SETTING_0', 'lingua generale del sito');
define('JAMMER_SETTING_1', 'orario indicato negli oggetti del sito');
define('JAMMER_SETTING_2', 'immagine rappresentativa dell&apos;utente');
define('JAMMER_SETTING_3', 'visualizzazione informazioni personali da parte di altri account');
define('JAMMER_SETTING_4', 'visualizzazione avatar da parte di altri account');
define('JAMMER_SETTING_5', 'visualizzazione da parte di altri utenti degli aggiornamenti di stato pubblicati e dei materiali condivisi sul proprio profilo');
define('JAMMER_SETTING_6', 'visualizzazione immagini caricate su proprio profilo');
define('JAMMER_SETTING_7', 'visualizzazione video caricati su proprio profilo');
define('JAMMER_SETTING_8', 'visualizzazione contenuti pubblicati da altri utenti su proprio profilo');
define('JAMMER_SETTING_9', 'visualizzazione contenuti pubblicati su altri profili');
define('JAMMER_SETTING_10','visualizzazione profilo all&apos;interno delle ricerche di altri utenti');
define('JAMMER_SETTING_11','ricezione proposte di contatto');
define('JAMMER_SETTING_12','autorizzazione a commentare gli elementi presenti nel proprio profilo');
define('JAMMER_SETTING_13','autorizzazione a commentare gli elementi presenti in altri profili');
define('JAMMER_SETTING_14','ricezione messaggi privati');
define('JAMMER_SETTING_15','nuovo post pubblicato su proprio profilo');
define('JAMMER_SETTING_16','nuovi commenti a post precedentemente commentato');
define('JAMMER_SETTING_17','nuovi commenti a post pubblicato su altro profilo');
define('JAMMER_SETTING_18','nuovi tag da approvare');
define('JAMMER_SETTING_19','nuovi tag approvati');
define('JAMMER_SETTING_20','nuovi commenti ai propri materiali (immagini/video/eventi)');
define('JAMMER_SETTING_21','nuovi commenti a materiali precedentemente commentati');
define('JAMMER_SETTING_22','nuove richieste di contatto approvate');
define('JAMMER_SETTING_23','nuovi commenti a un evento precedentemente commentato');
define('JAMMER_SETTING_24','nuova recensione ricevuta a un album');
define('JAMMER_SETTING_25','nuovo rating a un album');
define('JAMMER_SETTING_26','nuovo rating a un evento";');
define('JAMMER_SETTING_27','nuovo evento pubblicato di cui si &egrave; protagonista');
define('JAMMER_SETTING_28','nuovo livello di autorit&agrave; raggiunto/perso');
define('JAMMER_SETTING_29','nuovi badge conquistati');
define('JAMMER_SETTING_30','nuovo post pubblicato su proprio profilo');
define('JAMMER_SETTING_31','nuovi commenti a post precedentemente commentato');
define('JAMMER_SETTING_32','nuovi commenti a post pubblicato su altro profilo');
define('JAMMER_SETTING_33','nuovi tag da approvare');
define('JAMMER_SETTING_34','nuovi tag approvati');
define('JAMMER_SETTING_35','nuovi commenti ai propri materiali (immagini/video/eventi)');
define('JAMMER_SETTING_36','nuovi commenti a materiali precedentemente commentati');
define('JAMMER_SETTING_37','nuove richieste di contatto approvate');
define('JAMMER_SETTING_38','nuovi commenti a un evento precedentemente commentato');
define('JAMMER_SETTING_39','nuova recensione ricevuta a un album');
define('JAMMER_SETTING_40','nuovo rating a un album');
define('JAMMER_SETTING_41','nuovo rating a un evento');
define('JAMMER_SETTING_42','nuovo evento pubblicato di cui si &egrave; protagonista');
define('JAMMER_SETTING_43','nuovo livello di autorit&agrave; raggiunto/perso');
define('JAMMER_SETTING_44','nuovi badge conquistati');

//SETTINGS SPOTTER
define('SPOTTER_SETTING_0', 'lingua generale del sito');
define('SPOTTER_SETTING_1', 'orario indicato negli oggetti del sito');
define('SPOTTER_SETTING_2', 'immagine rappresentativa dell&apos;utente');
define('SPOTTER_SETTING_3', 'visualizzazione informazioni personali da parte di altri account');
define('SPOTTER_SETTING_4', 'visualizzazione avatar da parte di altri account');
define('SPOTTER_SETTING_5', 'visualizzazione da parte di altri utenti degli aggiornamenti di stato pubblicati e dei materiali condivisi sul proprio profilo');
define('SPOTTER_SETTING_6', 'visualizzazione immagini caricate su proprio profilo');
define('SPOTTER_SETTING_7', 'visualizzazione video caricati su proprio profilo');
define('SPOTTER_SETTING_8', 'visualizzazione contenuti pubblicati da altri utenti su proprio profilo');
define('SPOTTER_SETTING_9', 'visualizzazione contenuti pubblicati su altri profili');
define('SPOTTER_SETTING_10','visualizzazione profilo all&apos;interno delle ricerche di altri utenti');
define('SPOTTER_SETTING_11','ricezione proposte di contatto');
define('SPOTTER_SETTING_12','autorizzazione a commentare gli elementi presenti nel proprio profilo');
define('SPOTTER_SETTING_13','autorizzazione a commentare gli elementi presenti in altri profili');
define('SPOTTER_SETTING_14','ricezione messaggi privati');
define('SPOTTER_SETTING_15','nuovo post pubblicato su proprio profilo');
define('SPOTTER_SETTING_16','nuovi commenti a post precedentemente commentato');
define('SPOTTER_SETTING_17','nuovi commenti a post pubblicato su altro profilo') ;
define('SPOTTER_SETTING_18','nuovi tag da approvare');
define('SPOTTER_SETTING_19','nuovi tag approvati');
define('SPOTTER_SETTING_20','nuovi commenti ai propri materiali (immagini/video)');
define('SPOTTER_SETTING_21','nuovi commenti a materiali precedentemente commentati');
define('SPOTTER_SETTING_22','nuove richieste di contatto approvate');
define('SPOTTER_SETTING_23','nuovi commenti a un evento precedentemente commentato');
define('SPOTTER_SETTING_24','nuovi badge conquistati');
define('SPOTTER_SETTING_25','nuovo livello di autorit&agrave; raggiunto/perso');
define('SPOTTER_SETTING_26','nuovo rating a una recensione pubblicata');
define('SPOTTER_SETTING_27','nuovo post pubblicato su proprio profilo');
define('SPOTTER_SETTING_28','nuovi commenti a post precedentemente commentato');
define('SPOTTER_SETTING_29','nuovi commenti a post pubblicato su altro profilo');
define('SPOTTER_SETTING_30','nuovi tag da approvare');
define('SPOTTER_SETTING_31','nuovi tag approvati');
define('SPOTTER_SETTING_32','nuovi commenti ai propri materiali (immagini/video)');
define('SPOTTER_SETTING_33','nuovi commenti a materiali precedentemente commentati');
define('SPOTTER_SETTING_34','nuove richieste di contatto approvate');
define('SPOTTER_SETTING_35','nuovi commenti a un evento precedentemente commentato');
define('SPOTTER_SETTING_36','nuovi badge conquistati');
define('SPOTTER_SETTING_37','nuovo livello di autorit&agrave; raggiunto/perso');
define('SPOTTER_SETTING_38','nuovo rating a una recensione pubblicata');

//SETTINGS VENUE
define('VENUE_SETTING_0', 'lingua generale del sito');
define('VENUE_SETTING_1', 'orario indicato negli oggetti del sito');
define('VENUE_SETTING_2', 'immagine rappresentativa dell&apos;utente');
define('VENUE_SETTING_3', 'visualizzazione informazioni personali da parte di altri account');
define('VENUE_SETTING_4', 'visualizzazione avatar da parte di altri account');
define('VENUE_SETTING_5', 'visualizzazione da parte di altri utenti degli aggiornamenti di stato pubblicati e dei materiali condivisi sul proprio profilo');
define('VENUE_SETTING_6', 'visualizzazione immagini caricate su proprio profilo');
define('VENUE_SETTING_7', 'visualizzazione video caricati su proprio profilo');
define('VENUE_SETTING_8', 'visualizzazione contenuti pubblicati da altri utenti su proprio profilo');
define('VENUE_SETTING_9', 'visualizzazione contenuti pubblicati su altri profili');
define('VENUE_SETTING_10','visualizzazione profilo all&apos;interno delle ricerche di altri utenti');
define('VENUE_SETTING_11','ricezione proposte di contatto');
define('VENUE_SETTING_12','autorizzazione a commentare gli elementi presenti nel proprio profilo');
define('VENUE_SETTING_13','autorizzazione a commentare gli elementi presenti in altri profili');
define('VENUE_SETTING_14','ricezione messaggi privati');
define('VENUE_SETTING_15','nuovo post pubblicato su proprio profilo');
define('VENUE_SETTING_16','nuovi commenti a post precedentemente commentato');
define('VENUE_SETTING_17','nuovi commenti a post pubblicato su altro profilo');
define('VENUE_SETTING_18','nuovi tag da approvare');
define('VENUE_SETTING_19','nuovi tag approvati');
define('VENUE_SETTING_20','nuovi commenti ai propri materiali (immagini/video/eventi)');
define('VENUE_SETTING_21','nuovi commenti a materiali precedentemente commentati');
define('VENUE_SETTING_22','nuove richieste di contatto approvate');
define('VENUE_SETTING_23','nuovi commenti a un evento precedentemente commentato');
define('VENUE_SETTING_24','nuovo rating a un evento');
define('VENUE_SETTING_25','nuovo evento pubblicato di cui si &egrave; ospitante');
define('VENUE_SETTING_26','nuovo livello di autorit&agrave; raggiunto/perso');
define('VENUE_SETTING_27','nuovi badge conquistati');
define('VENUE_SETTING_28','nuovo post pubblicato su proprio profilo');
define('VENUE_SETTING_29','nuovi commenti a post precedentemente commentato');
define('VENUE_SETTING_30','nuovi commenti a post pubblicato su altro profilo');
define('VENUE_SETTING_31','nuovi tag da approvare');
define('VENUE_SETTING_32','nuovi tag approvati');
define('VENUE_SETTING_33','nuovi commenti ai propri materiali (immagini/video/eventi)');
define('VENUE_SETTING_34','nuovi commenti a materiali precedentemente commentati');
define('VENUE_SETTING_35','nuove richieste di contatto approvate');
define('VENUE_SETTING_36','nuovi commenti a un evento precedentemente commentato');
define('VENUE_SETTING_37','nuovo rating a un evento');
define('VENUE_SETTING_38','nuovo evento pubblicato di cui si &egrave; ospitante');
define('VENUE_SETTING_39','nuovo livello di autorit&agrave; raggiunto/perso');
define('VENUE_SETTING_40','nuovi badge conquistati');
?>